server.port=8081
channel-id=put your channel id here
eventsub.channel-id=${channel-id}
eventsub.client-id=put your client id here
eventsub.client-secret=put your client secret here
eventsub.channel-name=erst
eventsub.chat-bot-o-auth-token=put your chatbot oAuth token here
user.channel-id=${channel-id}
spring.datasource.url=jdbc:h2:C:/Stream/Runtime/playground/pg
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=pg
spring.datasource.password=d820j4e_33
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
lp.blacklist=erst,erstbot,streamelements,eve2twitch